# Generated by Django 2.0.8 on 2018-10-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='guidesImage', verbose_name='Miniatura')),
                ('content', models.TextField(verbose_name='Contenido de la guia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion')),
            ],
        ),
    ]
