# Generated by Django 2.0.8 on 2018-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_m', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion'),
        ),
    ]
