# Generated by Django 2.0.8 on 2018-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_m', '0004_auto_20180926_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_tag',
            field=models.CharField(choices=[('danger', 'Rojo'), ('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarillo')], max_length=2, verbose_name='Color de la etiqueta'),
        ),
    ]
